name: Project Shein CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Environment variables
env:
  NODE_VERSION: '18'
  CACHE_KEY_PREFIX: v1

jobs:
    validate-and-build:
        name: Validate and Build
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                persist-credentials: true
                fetch-depth: 0
            
            - name: Setup Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ env.NODE_VERSION }}
                cache: 'npm'
            
            - name: Install dependencies
              run: npm ci

            - name: Run linting
              run: |
                echo "Running code quality checks..."
                npm run lint || (echo "::warning ::Linting issues found" && exit 1)

            - name: Run unit tests
              run: npm test -- --watchAll=false
            
            - name: Build application
              run: |
                echo "Building production application..."
                npm run build
                
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build-output
                path: build/
                retention-days: 7